export enum Outcome {
    MEETS_CRITERIA = 'MEETS_CRITERIA',
    DOES_NOT_MEET_CRITERIA = 'DOES_NOT_MEET_CRITERIA',
    SPEAK_TO_GENETIC_COUNSELOR = 'SPEAK_TO_GENETIC_COUNSELOR',
    INCONCLUSIVE = 'INCONCLUSIVE'
};

export const FAMILY_TRACK = "FAMILY_TRACK";
